version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_net

  pagos:
    build:
      context: ./pagos
      dockerfile: Dockerfile
    container_name: pagos_service
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce_db
    networks:
      - ecommerce_net

  usuarios:
    build:
      context: ./usuarios
      dockerfile: Dockerfile
    container_name: usuarios_service
    restart: always
    ports:
      - "3002:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce_db
    networks:
      - ecommerce_net

  carrito:
    build:
      context: ./carrito
      dockerfile: Dockerfile
    container_name: carrito_service
    restart: always
    ports:
      - "3003:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce_db
    networks:
      - ecommerce_net

  pedido:
    build:
      context: ./pedido
      dockerfile: Dockerfile
    container_name: pedido_service
    restart: always
    ports:
      - "3004:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce_db
    networks:
      - ecommerce_net

  productos:
    build:
      context: ./productos
      dockerfile: Dockerfile
    container_name: productos_service
    restart: always
    ports:
      - "3005:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce_db
    networks:
      - ecommerce_net

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - pagos
      - usuarios
      - carrito
      - pedido
      - productos
    networks:
      - ecommerce_net

networks:
  ecommerce_net:

volumes:
  postgres_data:



