version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_net

  pagos:
    build: ./pagos
    container_name: pagos_service
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce_db
    networks:
      - ecommerce_net

  usuarios:
    build: ./usuarios
    container_name: usuarios_service
    ports:
      - "3002:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce_db
    networks:
      - ecommerce_net

  carrito:
    build: ./carrito
    container_name: carrito_service
    ports:
      - "3003:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce_db
    networks:
      - ecommerce_net

  pedido:
    build: ./pedido
    container_name: pedido_service
    ports:
      - "3004:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce_db
    networks:
      - ecommerce_net

  productos:
    build: ./productos
    container_name: productos_service
    ports:
      - "3005:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: ecommerce_db
    networks:
      - ecommerce_net

networks:
  ecommerce_net:

volumes:
  postgres_data:

